title: "Uniorb"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
logo: "/assets/images/logo.png"
aux_links:
  "Uniorb on GitHub":
    - "https://github.com/uniorb/uniorb"
google_analytics: G-FNMBNFT0T3
